---
- name: Create required Dirs
  ansible.builtin.shell: |
    mkdir -p /etc/nginx/sites-available
    chmod 777 /etc/nginx/sites-available

- name: install Nginx
  yum:
    name: nginx
    state: present
  notify: nginx restart

- name: Copy default config
  copy:
    src: default.conf
    dest: /etc/nginx/sites-available/default.conf
  notify: nginx restart

- name: Copy nginx confi using template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: nginx restart

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
