---
- name: performs multiple tasks
  hosts: my_server
  become: yes
  tasks:
    - name: listing files from home
      shell: ls -ltr /home/installer
      register: file_list
    - name: printing the file list
      debug:
        var: file_list.stdout
    - name: installing multipl packages
      yum:
        name: "{{ item }}""
        state: present
      loop:
        - git
        - docker
        - wget
    - name: Docker successuflly installed
      debug:
        msg: "docker is installed and is ready"
